/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset ackley --kernel rbf --seed 0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset ackley --kernel matern --seed 0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_mc --dim 2 --N 25 --dataset ackley --kernel rbf --seed 0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset ackley --kernel rbf --seed 1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset ackley --kernel matern --seed 1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_mc --dim 2 --N 25 --dataset ackley --kernel rbf --seed 1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset ackley --kernel matern --seed 2
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset ackley --kernel rbf --seed 2
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_mc --dim 2 --N 25 --dataset ackley --kernel rbf --seed 2
