/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset branin --kernel rbf --seed 0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset branin --kernel matern --seed 0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_mc --dim 2 --N 25 --dataset branin --kernel rbf --seed 0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset branin --kernel rbf --seed 1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset branin --kernel matern --seed 1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_mc --dim 2 --N 25 --dataset branin --kernel rbf --seed 1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset branin --kernel matern --seed 2
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset branin --kernel rbf --seed 2
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_mc --dim 2 --N 25 --dataset branin --kernel rbf --seed 2
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset branin --kernel rbf --seed 4
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset branin --kernel matern --seed 4
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_mc --dim 2 --N 25 --dataset branin --kernel rbf --seed 4
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset branin --kernel rbf --seed 5
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset branin --kernel matern --seed 5
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_mc --dim 2 --N 25 --dataset branin --kernel rbf --seed 5
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset branin --kernel matern --seed 6
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_kq --dim 2 --N 25 --dataset branin --kernel rbf --seed 6
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python BO.py --utility EI_look_ahead_mc --dim 2 --N 25 --dataset branin --kernel rbf --seed 6
