#!/bin/bash
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 0 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 1 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 2 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 3 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 4 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 5 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 6 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 7 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 8 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 9 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 10 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 11 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 12 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 13 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 14 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 15 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 16 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 17 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 18 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 19 
/home/zongchen/miniconda3/envs/cbq/bin/python finance.py --seed 20 