#!/bin/bash
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 0 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 1 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 2 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 3 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 4 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 6 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 7 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 8 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 9 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 10 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 11 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 12 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 13 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 14 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 15 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 16 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 17 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 18 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 19 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 20 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 0.1
#!/bin/bash
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 0 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 1 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 2 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 3 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 4 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 6 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 7 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 8 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 9 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 10 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 11 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 12 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 13 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 14 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 15 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 16 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 17 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 18 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 19 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 20 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0 --d 1 --scale 1.0
