#!/bin/bash
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 0 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 1 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 2 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 3 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 4 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 5 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 6 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 7 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 8 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 9 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 10 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 11 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 12 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 13 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 14 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 15 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 16 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 17 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 18 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 19 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 20 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 21 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 22 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 23 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 24 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 25 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 26 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 27 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 28 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 29 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 30 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 31 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 32 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 33 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 34 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 35 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 36 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 37 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 38 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 39 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 40 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 41 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 42 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 43 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 44 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 45 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 46 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 47 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 48 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 49 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 50 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 51 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 52 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 53 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 54 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 55 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 56 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 57 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 58 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 59 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 60 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 61 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 62 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 63 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 64 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 65 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 66 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 67 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 68 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 69 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 70 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 71 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 72 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 73 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 74 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 75 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 76 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 77 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 78 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 79 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 80 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 81 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 82 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 83 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 84 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 85 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 86 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 87 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 88 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 89 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 90 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 91 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 92 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 93 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 94 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 95 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 96 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 97 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 98 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 99 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0
/home/zongchen/miniconda3/envs/look_ahead_bo/bin/python toy.py --seed 100 --d 5 --kernel_x matern --kernel_theta matern --N_T_ratio 1.0

