#!/bin/bash
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 0 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 1 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 2 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 3 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 4 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 5 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 6 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 7 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 8 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 9 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 10 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 11 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 12 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 13 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 14 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 15 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 16 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 17 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 18 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 19 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 20 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 21 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 22 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 23 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 24 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 25 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 26 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 27 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 28 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 29 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 30 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 31 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 32 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 33 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 34 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 35 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 36 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 37 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 38 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 39 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 40 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 41 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 42 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 43 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 44 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 45 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 46 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 47 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 48 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 49 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 50 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 51 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 52 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 53 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 54 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 55 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 56 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 57 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 58 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 59 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 60 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 61 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 62 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 63 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 64 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 65 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 66 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 67 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 68 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 69 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 70 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 71 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 72 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 73 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 74 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 75 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 76 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 77 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 78 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 79 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 80 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 81 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 82 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 83 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 84 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 85 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 86 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 87 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 88 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 89 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 90 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 91 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 92 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 93 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 94 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 95 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 96 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 97 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 98 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 99 --kernel_x matern --kernel_theta matern
/home/zongchen/miniconda3/envs/cbq/bin/python toy.py --seed 100 --kernel_x matern --kernel_theta matern
